Começo da Tradução
radarbot-team/radarbot-docs pull request #12
Opened 2022-01-27 18:33 UTC by Enrico1108

2022-02-05 19:19 UTC, andrebrito16 requested changes
Olá Enrico, tudo bem? Deixei comentários e solicitações de mudanças. Obrigado pela ajuda!

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/index.md
> +        Um bot Discord avançado em vários idiomas Feito por amantes da simulação de voo para amantes da simulação de voo [Convide RadarBot](https://bit.ly/RadarBotInvite)
pode ser "adicione o RadarBot ao seu servidor" ao invés de "Convide RadarBot"

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/acknowledgment.md
> +**Desenvolvimento do core RadarBot:**
"Desenvolvimento do core e criador do RadarBot"

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/commands/General.md
> +*Se você quer ajudar no desenvolvimento e continuar online 24 horas por dia, temos as opções  de Paypal ou ainda você pode ser um MemberShip Radar Bot, tendo benefícios como Posição de Apoiador no se
"MemberShip" -> "Membership"

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/commands/General.md
> +*Para saber a qualidade da sua internet diretamente no discord, use o comando ping do Radar Bot, ele informará seu Ping em relação ao Gateway*
"Para saber a qualidade da sua internet diretamente no discord" -> "Para saber o tempo de resposta do bot"

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/commands/Help.md
> +*O comando help mostra os comandos disponíveis no servidor, possui uma navegação emoji onde você pode entrar e sair das páginas, os comandos são divididos em categorias, as mesmas categorias deste do
Pontuação e substituir "docs" por "desta documentação"

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/commands/Vatsim.md
> +*Neste comando você coloca uma localização, no meu caso estou colocando um ICAO SB, o bot irá buscar as informações da API do Vatsim e mostrará todas as posições ativas com essas iniciais*
"no meu caso estou colocando" -> "neste caso foi colocado"
Dica: **nunca** usar primeira pessoa na escrita de documentações e guias, sempre terceira pessoa

2022-02-05 19:19 UTC, andrebrito16 commented on docs/radarbot-pt/index.md
> +        Um bot Discord avançado em vários idiomas Feito por amantes da simulação de voo para amantes da simulação de voo [Convide RadarBot](https://bit.ly/RadarBotInvite)
"Feito" -> "feito"

2022-02-05 20:14 UTC, Enrico1108 commented
> Olá Enrico, tudo bem? Deixei comentários e solicitações de mudanças. Obrigado pela ajuda!

Oi Felipe Correções feitas

2022-02-06 23:49 UTC, andrebrito16 approved these changes

2022-02-06 23:49 UTC, merged